### PR TITLE
RHMAP-2596 Update fh-sdk to 1.3.3

### PR DESCRIPTION
**Pull request by david-martin**

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@david-martin NuGet dep, so this looks right (even though this is not published yet)

**Comment by david-martin** [comment]
@wei-lee @edewit 
Are there other changes required for this sdk bump?
This repo has a project.lock.json. Does it need to be regenerated somehow?

**Comment by wei-lee** [comment]
LGTM. @edewit  any idea about the project.lock.json file?

**Comment by edewit** [comment]
:+1: that is new I think you can use it to lock down versions it's generated off the project.json file guess we could remove it from source control

**Comment by david-martin** [comment]
@edewit removed the lockfile & cherry-picked the appveyor.yml

**Comment by david-martin** [comment]
merged via https://github.com/feedhenry-templates/fh-csharp-window-10-blank-app/pull/6

**Pull request closed without merging**
